COQDOCJS_DIR ?= coqdocjs
EXTRA_DIR = $(COQDOCJS_DIR)/extra
COQDOCFLAGS ?= \
  $(COQDOCFLAGS_EXTRA) \
  --toc --toc-depth 2 --html --interpolate \
  --index indexpage --no-lib-name --parse-comments \
  --with-header $(EXTRA_DIR)/header.html --with-footer $(EXTRA_DIR)/footer.html
export COQDOCFLAGS
COQMAKEFILE ?= Makefile.coq
COQDOCJS_CP ?= false

html: $(COQMAKEFILE)
	$(MAKE) -f $^ $@
ifeq ($(COQDOCJS_CP),true)
	cp -R $(EXTRA_DIR)/resources $@
else
	ln -sf ../$(EXTRA_DIR)/resources $@
endif

.PHONY: html
